const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
const USER_CREATED_SUCCESSFULLY = 'USER_CREATED_SUCCESSFULLY';
const USER_CREATED_ERROR = 'USER_CREATED_ERROR';
const USER_LOGIN_SUCCESSFULLY = 'USER_LOGIN_SUCCESSFULLY';
const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
const RESET_ALERT = 'RESET_ALERT';


/**
 * Expose reducer types
 */
export {
  USER_AUTHENTICATED,
  USER_CREATED_SUCCESSFULLY,
  USER_CREATED_ERROR,
  USER_LOGIN_SUCCESSFULLY,
  USER_LOGIN_ERROR,
  RESET_ALERT
}